### ISSUE TITLE
[ripgrep] - Upgrade Package to 14

### ISSUE THREAD

**Issue by mattcargile** [dstcruz/chocolatey-mypackages#6]
See title. Current build is version 13.

**Comment by dstcruz** [comment]
@mattcargile, would you be able to help upgrading this? I can share access to it, or however it is done is chocolatey, to allow you to do it. I'm currently traveling out of the country, without good connection, and without tools (machine, environments, etc). I hate to hold this up.

**Comment by corbob** [comment]
@dstcruz I've opened PR #7 which should resolve this issue. I'm not sure if you have automation setup to automatically push the packages up to Chocolatey Community Repository (CCR) or not, but presuming you do, I imagine the PR being merged will update this on CCR. If you don't have automation setup, I would be more than happy to be added as a maintainer on CCR and get it pushed up. My username on CCR is [corbob](https://community.chocolatey.org/profiles/corbob) just like here.

**Comment by dstcruz** [comment]
@corbob, let me see how I can add you as a maintainer. You are right, I don't have automation set up for pushing this to CCR, and your help at this junction would be greatly appreciated!

**Comment by dstcruz** [comment]
@corbob, I have added you as a maintainer in CCR. I see that there is a "pending approval" state. I'm not familiar if that's an approval from CCR admins, from you, or maybe even an email for me. I will be around for an hour more here, and then again tomorrow evening/night.

**Comment by corbob** [comment]
@dstcruz I've gotten the email. Pretty sure all that's needed is for me to hit the link. I'll get that done when I'm at the computer tomorrow and then should be able to get the package pushed up. If I get a chance on the weekend I might take a look at what's needed to get a GitHub action to do the update checks and push for you.
